### ISSUE TITLE
iubeo not return in for loop 

### ISSUE THREAD

**Issue by aliemresafak** [isik-kaplan/iubeo#4]
Hey, second code block doesn't work

```py
from iubeo import config

COMPANY_TEMPLATE = {"HOST": str, "PORT": int, "USER": str, "PASS": str}

CONFIG = config(
    {
        "FTP": {
            "X": COMPANY_TEMPLATE
            "B": COMPANY_TEMPLATE
        },
    }
)

print(CONFIG.FTP.X.HOST) # It works
```

```py
for key, value in CONFIG.FTP.items():
    print(CONFIG.FTP.get(key).get("HOST"))`
```
The output of the above code
``
['FTP__X__HOST', <class 'str'>]
``

All the best

**Comment by isik-kaplan** [comment]
Hmm, given that I've never needed to loop through the configuration I just assumed that it would be only accessed via the end node, should be simple as budging a new layer on top that actually runs through the entire config and reconstructs the configuration. This also would allow me to add the read-only feature to the configuration objects.

Will fix it in a minor version. Nice one, thanks!

**Comment by isik-kaplan** [comment]
https://github.com/isik-kaplan/iubeo/pull/9
